### ISSUE TITLE
Why is Jenkins not on the list of top technologies?

### ISSUE THREAD

**Issue by mr-joshcrane** [t04glovern/linkedin-professional#2]
Jenkins is a fantastic piece of software. It only gets a bad name because of  the way he is writing it. The story is interesting and it has a lot of interesting characters and a lot of interesting things going on. The novel has a lot of nice details too.The second part is a lot of love for one of my favorite games in all of gaming, the role learning game RTS RTS. This one is a bit of a treat for me. The storyline has a lot of interesting twists and turns. It's almost fun to read, but don't put the time on it unless you have a lot of time. For me, this one is also quite enjoyable.The third part has me so happy because I really missed the beginning of the story. There were scenes in the story where I didn't fully understand how the story progressed but I've been using it really well to read into my feelings for this one. This really is a pleasure to read.

**Comment by t04glovern** [comment]
All very valid points but I don't care

**Comment by mr-joshcrane** [comment]
This is an outrage I pay my taxes on but in any case as you've said, I don't want my kids to go into a school for a few hours at a time, and yet we don't have the time, the resources, the support to do that. We only want the kids to do what is best with their families and to do this without being bullied and pushed around. I don't want that child to be bullied at school. We have to keep our kids safe from that as well and my plan is to work with the federal government on that issue, which is to pass a bill through the legislature with an amendment that would create an independent school choice committee and then make sure that our kids go to school."

Watch the video in its entirety below:

**Comment by t04glovern** [comment]
https://www.youtube.com/watch?v=YBCq8XDgrP0
